import { useState, useRef, useEffect } from 'react'
import { Send, Bot, User, Sparkles, Maximize2, Minimize2 } from 'lucide-react'

interface Message {
    id: string
    role: 'user' | 'assistant'
    content: string
    timestamp: Date
}

const INITIAL_MESSAGES: Message[] = [
    {
        id: 'init-1',
        role: 'assistant',
        content: `Hey Nabeel 👋 I'm your Claude co-worker. I have access to your GitHub repos, Supabase database, Notion workspace, and all connected services.\n\nI can help with:\n• Reviewing and editing content before publishing\n• Pulling data from any connected service\n• Updating tasks, deals, or contacts\n• Running agent operations\n• Syncing changes across tools\n\nWhat would you like me to do?`,
        timestamp: new Date(),
    },
]

// Simulated responses based on keywords
function getSimulatedResponse(input: string): string {
    const lower = input.toLowerCase()

    if (lower.includes('linkedin') || lower.includes('post')) {
        return `I see 3 LinkedIn posts pending your approval in the queue — all generated by NanoBanana:\n\n1. **"Why Pakistan is the Next EOR Frontier"** — thought leadership piece\n2. **"Client Success Story — TechScale"** — case study\n3. **"EOBI Compliance Tips"** — educational content\n\nYou can approve them from the Marketing → LinkedIn tab, or I can schedule them for you. Want me to set up a posting schedule?`
    }

    if (lower.includes('supabase') || lower.includes('database') || lower.includes('data')) {
        return `Your Supabase instance is connected and healthy. Here's a quick snapshot:\n\n• **Agents**: 9 active (all online)\n• **Deals**: 3 in pipeline ($17,700 MRR)\n• **Tasks**: Active across all departments\n• **Activity Log**: Last entry 2 hours ago\n\nWant me to query something specific or update any records?`
    }

    if (lower.includes('notion') || lower.includes('task')) {
        return `I can sync your task updates to Notion. Here's what's pending:\n\n• Update the department tools config in Notion\n• Post the latest milestone update\n• Set up the daily report automation\n\nI'll queue these in my task file at \`.claude/tasks/\`. Want me to proceed?`
    }

    if (lower.includes('github') || lower.includes('deploy') || lower.includes('push')) {
        return `Your latest push to \`main\` (commit \`e32b752\`) deployed successfully. The dashboard is running at localhost:5173.\n\nRecent commits:\n• Department budget & tools system\n• 12-month P&L spreadsheet\n• MCP status banner + reconnect buttons\n\nWant me to create a PR, tag a release, or check deployment status?`
    }

    if (lower.includes('budget') || lower.includes('spend') || lower.includes('cost')) {
        return `Here's your current tool budget breakdown:\n\n| Dept | Budget | Spend | Status |\n|------|--------|-------|--------|\n| Sales | $80 | $87.49 | ⚠️ Over |\n| Marketing | $60 | $35.50 | ✅ Under |\n| Infra | $60 | $68.00 | ⚠️ Over |\n\n**Total**: $190.99 / $200 (95.5% utilized)\n\nSales is $7.49 over budget mainly due to LinkedIn Sales Navigator ($49.99). Want me to suggest optimizations?`
    }

    return `Got it. I'll look into that. In the meantime, you can:\n\n• Check the **Marketing → LinkedIn** tab for pending posts\n• Review the **Finance → P&L** tab for your 12-month view\n• Use the **Task Board** to see all department tasks\n\nIs there anything specific you'd like me to action across your connected services (GitHub, Supabase, Notion)?`
}

interface ClaudeChatProps {
    /** If true, renders as a compact inline panel */
    inline?: boolean
}

export default function ClaudeChat({ inline }: ClaudeChatProps) {
    const [messages, setMessages] = useState<Message[]>(INITIAL_MESSAGES)
    const [input, setInput] = useState('')
    const [isTyping, setIsTyping] = useState(false)
    const [expanded, setExpanded] = useState(false)
    const messagesEndRef = useRef<HTMLDivElement>(null)
    const inputRef = useRef<HTMLTextAreaElement>(null)

    useEffect(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
    }, [messages, isTyping])

    const handleSend = () => {
        if (!input.trim()) return

        const userMsg: Message = {
            id: `msg-${Date.now()}`,
            role: 'user',
            content: input.trim(),
            timestamp: new Date(),
        }
        setMessages((prev) => [...prev, userMsg])
        setInput('')
        setIsTyping(true)

        // Simulate response delay
        setTimeout(() => {
            const response: Message = {
                id: `msg-${Date.now()}-resp`,
                role: 'assistant',
                content: getSimulatedResponse(userMsg.content),
                timestamp: new Date(),
            }
            setMessages((prev) => [...prev, response])
            setIsTyping(false)
        }, 800 + Math.random() * 1200)
    }

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault()
            handleSend()
        }
    }

    const containerHeight = inline
        ? expanded ? 'h-[600px]' : 'h-[400px]'
        : 'h-[calc(100vh-200px)]'

    return (
        <div className={`flex flex-col ${containerHeight} bg-white rounded-xl border border-light-gray/50 shadow-sm overflow-hidden transition-all duration-300`}>
            {/* Header */}
            <div className="flex items-center justify-between px-4 py-3 bg-gradient-to-r from-navy to-navy/90 text-white flex-shrink-0">
                <div className="flex items-center gap-2">
                    <div className="w-7 h-7 rounded-lg bg-white/15 flex items-center justify-center">
                        <Bot size={16} />
                    </div>
                    <div>
                        <div className="text-sm font-semibold">Claude Co-worker</div>
                        <div className="text-[10px] text-white/60 flex items-center gap-1">
                            <span className="w-1.5 h-1.5 rounded-full bg-teal animate-pulse" />
                            Connected to GitHub, Supabase, Notion
                        </div>
                    </div>
                </div>
                {inline && (
                    <button
                        onClick={() => setExpanded(!expanded)}
                        className="w-7 h-7 rounded-lg bg-white/10 hover:bg-white/20 flex items-center justify-center transition-colors"
                    >
                        {expanded ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
                    </button>
                )}
            </div>

            {/* Messages */}
            <div className="flex-1 overflow-y-auto px-4 py-4 space-y-4 scrollbar-thin">
                {messages.map((msg) => (
                    <div
                        key={msg.id}
                        className={`flex gap-2.5 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}
                    >
                        <div className={`
                            w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5
                            ${msg.role === 'user' ? 'bg-teal/10' : 'bg-navy/10'}
                        `}>
                            {msg.role === 'user'
                                ? <User size={14} className="text-teal" />
                                : <Sparkles size={14} className="text-navy" />
                            }
                        </div>
                        <div className={`
                            max-w-[80%] rounded-xl px-3.5 py-2.5
                            ${msg.role === 'user'
                                ? 'bg-teal text-white rounded-tr-sm'
                                : 'bg-surface text-navy rounded-tl-sm'
                            }
                        `}>
                            <div className="text-[13px] leading-relaxed whitespace-pre-wrap">
                                {msg.content}
                            </div>
                            <div className={`text-[9px] mt-1 ${msg.role === 'user' ? 'text-white/50' : 'text-charcoal/30'}`}>
                                {msg.timestamp.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                            </div>
                        </div>
                    </div>
                ))}

                {isTyping && (
                    <div className="flex gap-2.5">
                        <div className="w-7 h-7 rounded-lg bg-navy/10 flex items-center justify-center flex-shrink-0">
                            <Sparkles size={14} className="text-navy" />
                        </div>
                        <div className="bg-surface rounded-xl rounded-tl-sm px-4 py-3">
                            <div className="flex gap-1">
                                <span className="w-1.5 h-1.5 rounded-full bg-charcoal/30 animate-bounce" style={{ animationDelay: '0ms' }} />
                                <span className="w-1.5 h-1.5 rounded-full bg-charcoal/30 animate-bounce" style={{ animationDelay: '150ms' }} />
                                <span className="w-1.5 h-1.5 rounded-full bg-charcoal/30 animate-bounce" style={{ animationDelay: '300ms' }} />
                            </div>
                        </div>
                    </div>
                )}
                <div ref={messagesEndRef} />
            </div>

            {/* Input */}
            <div className="px-3 pb-3 flex-shrink-0">
                <div className="flex items-end gap-2 bg-surface rounded-xl border border-light-gray/30 px-3 py-2 focus-within:border-teal/40 focus-within:ring-2 focus-within:ring-teal/10 transition-all">
                    <textarea
                        ref={inputRef}
                        value={input}
                        onChange={(e) => setInput(e.target.value)}
                        onKeyDown={handleKeyDown}
                        rows={1}
                        className="flex-1 bg-transparent text-sm text-navy placeholder:text-charcoal/30 outline-none resize-none max-h-24"
                        placeholder="Ask Claude anything... (⏎ to send)"
                    />
                    <button
                        onClick={handleSend}
                        disabled={!input.trim() || isTyping}
                        className={`
                            w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 transition-all
                            ${input.trim() && !isTyping
                                ? 'bg-teal text-white hover:bg-teal/90 shadow-sm'
                                : 'bg-light-gray/50 text-charcoal/30'
                            }
                        `}
                    >
                        <Send size={14} />
                    </button>
                </div>
                <div className="text-[9px] text-charcoal/25 text-center mt-1.5">
                    Claude has access to GitHub, Supabase, Notion, and all MCP services
                </div>
            </div>
        </div>
    )
}
